#!/usr/bin/env python3
"""Task 2 — assemble a markdown report from the sweep + baseline CSVs.

Reads `artifacts/tokenizer_sweep/{results,baseline_comparison}.csv`
(produced by `scripts/sweep_vocab_size.py` and
`scripts/compare_baselines.py` -- run those first), renders the charts
in `src/tokenizer/report.py`, and writes a self-contained
`artifacts/tokenizer_sweep/report.md` with the methodology, the numbers,
and the plots embedded -- so re-running the sweep with different data
(e.g. the full non-pilot corpus) regenerates a report that matches,
rather than a hand-written doc that drifts.

Vocab size is auto-picked by `pick_chosen_vocab_size` (Kneedle elbow
detection on the compression curve -- see its docstring) unless
`--chosen-vocab-size` overrides it. Embedding-param cost is reported as
context (compared against real Llama 3 small-model precedent on the
tradeoff chart), not as an automated gate.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.tokenizer.report import (
    pick_chosen_vocab_size,
    plot_baseline_comparison,
    plot_cost_vs_model_scale,
    plot_sweep_compression,
    plot_sweep_marginal_gain,
    plot_sweep_tradeoff,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def _read_csv(path: Path, float_cols: list[str], int_cols: list[str]) -> list[dict]:
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        for col in float_cols:
            row[col] = float(row[col])
        for col in int_cols:
            row[col] = int(row[col])
    return rows


def generate_report(
    sweep_csv: Path,
    baseline_csv: Path | None,
    chosen_vocab_size: int | None,
    out_dir: Path,
) -> Path:
    sweep_rows = _read_csv(
        sweep_csv, float_cols=["fertility", "compression_ratio", "embedding_param_share"], int_cols=["vocab_size"]
    )
    vocab_size = chosen_vocab_size if chosen_vocab_size is not None else pick_chosen_vocab_size(sweep_rows)

    out_dir.mkdir(parents=True, exist_ok=True)
    plot_sweep_compression(sweep_rows, vocab_size, out_dir / "sweep_compression.png")
    plot_sweep_marginal_gain(sweep_rows, vocab_size, out_dir / "sweep_marginal_gain.png")
    plot_sweep_tradeoff(sweep_rows, vocab_size, out_dir / "sweep_tradeoff.png")
    plot_cost_vs_model_scale(vocab_size, out_dir / "cost_vs_model_scale.png")

    baseline_rows = None
    if baseline_csv is not None and baseline_csv.exists():
        baseline_rows = _read_csv(
            baseline_csv, float_cols=["fertility", "compression_ratio"], int_cols=["vocab_size"]
        )
        plot_baseline_comparison(baseline_rows, out_dir / "baseline_comparison.png")

    report_path = out_dir / "report.md"
    report_path.write_text(_render_markdown(sweep_rows, baseline_rows, vocab_size))
    print(f"Wrote {report_path}")
    return report_path


def _render_markdown(sweep_rows: list[dict], baseline_rows: list[dict] | None, chosen_vocab_size: int) -> str:
    vocab_sizes = sorted({r["vocab_size"] for r in sweep_rows})
    overall = {r["vocab_size"]: r for r in sweep_rows if r["lang"] == "overall"}

    lines = [
        "# Tokenizer vocab-size decision report",
        "",
        "Auto-generated by `scripts/generate_report.py` from "
        "`artifacts/tokenizer_sweep/{results,baseline_comparison}.csv` -- "
        "re-run the sweep + this script together; don't hand-edit this file.",
        "",
        "## Methodology",
        "",
        f"- Candidate vocab sizes swept: {', '.join(f'{v:,}' for v in vocab_sizes)}.",
        "- Each candidate trained on a fixed-size, per-language-stratified "
        "sample (`scripts/sweep_vocab_size.py --train-sample-mb`), evaluated "
        "on a disjoint held-out sample of the same kind -- so these numbers "
        "are never in-sample.",
        "- Decision rule: the Kneedle algorithm's elbow on the overall "
        "compression-vs-vocab-size curve (`src/tokenizer/report.py::pick_chosen_vocab_size`) "
        "-- not an asserted \"gain < X%\" threshold.",
        "- Embedding-param cost (embedding_param_share) is reported as "
        "context, not an automated gate. This project has **not decided a "
        "target pre-training model size** -- the CSV's embedding_param_share "
        "column is computed against one fixed illustrative anchor "
        "(GPT-2-Small: hidden_dim=768, 124M params), not a real target, so "
        "the tradeoff chart is explicitly labeled as a single-anchor view "
        "and paired with a second chart showing the same chosen vocab "
        "size's cost across five real published model scales (GPT-2-Small/"
        "Large, Llama-3.2-1B/3B, Llama-3.1-8B) -- the share swings from "
        "~20% to ~1% across that range, so \"the cost\" isn't one number "
        "until a target model is chosen.",
        f"- **Chosen: vocab_size = {chosen_vocab_size:,}** "
        f"(embedding_param_share = {overall[chosen_vocab_size]['embedding_param_share']:.1%}, "
        f"overall compression = {overall[chosen_vocab_size]['compression_ratio']:.3f} bytes/token).",
        "",
        "## Sweep results",
        "",
        "![Compression vs. vocab size, by language](sweep_compression.png)",
        "",
        "Per-language compression curves. Hindi (hi) barely moves across "
        "the whole sweep while pt/es keep improving -- a sign that hi is "
        "*data*-starved rather than *vocab*-starved at this corpus size; a "
        "bigger vocab alone won't fix it.",
        "",
        "![Marginal gain per vocab-size doubling](sweep_marginal_gain.png)",
        "",
        "Marginal compression gain at each doubling; the accent bar is the "
        "Kneedle-chosen elbow. No threshold line here -- the elbow is a "
        "curvature property of the whole curve, not a per-step cutoff.",
        "",
        "![Compression vs. embedding-param cost](sweep_tradeoff.png)",
        "",
        "Compression benefit vs. embedding-param cost, but the x-axis is "
        "**one fixed anchor (GPT-2-Small scale)** -- see the chart below "
        "for how much that number actually depends on model size. Real "
        "Llama-3.2 1B/3B tied-embedding shares are drawn as reference "
        "lines instead of an asserted ceiling. The chosen size is "
        "outlined and bold.",
        "",
        "![Cost of the chosen vocab size across real model scales](cost_vs_model_scale.png)",
        "",
        "The actual point: this project hasn't picked a target model "
        "size, so the cost of the chosen vocab size isn't one number -- "
        "see the chart's own bar labels for the exact range across "
        "GPT-2-Small through Llama-3.1-8B scale. Revisit once the "
        "pre-training model's architecture is decided.",
        "",
        "| vocab_size | lang | fertility | compression_ratio | embedding_param_share |",
        "|---:|---|---:|---:|---:|",
    ]
    for r in sorted(sweep_rows, key=lambda r: (r["vocab_size"], r["lang"])):
        lines.append(
            f"| {r['vocab_size']:,} | {r['lang']} | {r['fertility']:.3f} | "
            f"{r['compression_ratio']:.3f} | {r['embedding_param_share']:.1%} |"
        )

    if baseline_rows is not None:
        lines += [
            "",
            "## Baseline comparison",
            "",
            "![Compression ratio by tokenizer and language](baseline_comparison.png)",
            "",
            "All tokenizers evaluated zero-shot on the same disjoint "
            "held-out sample as the sweep -- the `ours` row here is a "
            "freshly trained tokenizer on the sweep's train bucket, not "
            "the shipped artifact (which is trained on the full corpus "
            "and would be in-sample if evaluated here).",
            "",
            "| tokenizer | vocab_size | lang | fertility | compression_ratio |",
            "|---|---:|---|---:|---:|",
        ]
        for r in sorted(baseline_rows, key=lambda r: (r["tokenizer"], r["lang"])):
            lines.append(
                f"| {r['tokenizer']} | {r['vocab_size']:,} | {r['lang']} | "
                f"{r['fertility']:.3f} | {r['compression_ratio']:.3f} |"
            )

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sweep-csv", type=Path, default=REPO_ROOT / "artifacts" / "tokenizer_sweep" / "results.csv")
    parser.add_argument(
        "--baseline-csv", type=Path, default=REPO_ROOT / "artifacts" / "tokenizer_sweep" / "baseline_comparison.csv"
    )
    parser.add_argument(
        "--chosen-vocab-size", type=int, default=None, help="Override the Kneedle-picked size (must match a swept candidate)"
    )
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "artifacts" / "tokenizer_sweep")
    args = parser.parse_args()

    generate_report(
        sweep_csv=args.sweep_csv,
        baseline_csv=args.baseline_csv,
        chosen_vocab_size=args.chosen_vocab_size,
        out_dir=args.out_dir,
    )
